# Generated by Django 5.1.6 on 2025-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ripe_count', models.IntegerField(default=0)),
                ('raw_count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='counting_images/')),
                ('status', models.CharField(default='stopped', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PalmOilCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('suitable_count', models.IntegerField(default=0)),
                ('unsuitable_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='stopped', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='palm_oil_images/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
